menu:
  - name: Home
    url: /
  - name: Archives
    url: /archives
  - name: Categories
    url: /categories
  - name: Tags
    url: /tags
  - name: About
    url: /about
  - name: RSS
    url: /rss.xml

sidebar:
  enable: true
  widgets:
    - search
    - notice
    - categories
    - tags
    - links
    

  numlimit: # 限制显示的数量
    categories: 5
    tags: 10
  links:
    - name: 百度
      url: https://www.baidu.com
  notice: # 公告栏内容
    enable: true # 设置为 true 启用，false 禁用
    content: "博客正在进行优化，敬请期待更多内容！" # 公告栏显示的内容

